-- ============================================================
-- 企業マスタ＋候補者パイプライン 拡張 ＆ エクセル実データ取込
-- Supabase SQL Editor で実行（既存スキーマ適用済みの前提）
-- ============================================================

alter table companies  add column if not exists info     jsonb default '{}'::jsonb;
alter table companies  add column if not exists contacts jsonb default '[]'::jsonb;
alter table candidates add column if not exists pipeline jsonb default '{}'::jsonb;
alter table candidates add column if not exists batch    text;

delete from app_users where company_id in ('c1','c2','c3') or candidate_id in ('p1','p2','p3','p4','p5');
delete from candidates where id in ('p1','p2','p3','p4','p5');
delete from companies  where id in ('c1','c2','c3');

-- 企業マスタ
insert into companies (id,name,info,contacts) values ('11435','株式会社エコランド','{"area": "東京", "features": "豆鉄砲", "vehicles": "18台（4tトラック2台、2tトラック10台、自家用6台）", "country": "インドネシア", "followup": "2024Indonesia視察/2026/2面接", "headcount": "2(2025)＋２(2026)"}'::jsonb,'[{"name": "高嶋民仁", "role": "代表取締役社長", "email": "tamihito@winroader.co.jp"}, {"name": "志村", "role": "★実務者", "email": "shimura@eco-land.co.jp"}]'::jsonb) on conflict (id) do update set name=excluded.name, info=excluded.info, contacts=excluded.contacts;
insert into companies (id,name,info,contacts) values ('C11550','株式会社ウインローダー','{}'::jsonb,'[{"name": "飯島 大貴", "role": "★実務者（初期のみ）", "email": "d_iijima@winroader.co.jp"}]'::jsonb) on conflict (id) do update set name=excluded.name, info=excluded.info, contacts=excluded.contacts;
insert into companies (id,name,info,contacts) values ('11433','株式会社サンウエイ','{"area": "東京", "features": "豆鉄砲", "country": "インドネシア", "followup": "2024Indonesia視察/2026/2面接", "headcount": "2(2025)＋２(2026)"}'::jsonb,'[{"name": "高嶋", "role": "代表取締役会長", "email": "tamihito@winroader.co.jp"}, {"name": "十倉", "role": "★実務者", "email": "tokura@sunway1929.co.jp"}, {"name": "明石", "role": "★実務者　管理部", "email": "akashi@sunway1929.co.jp"}]'::jsonb) on conflict (id) do update set name=excluded.name, info=excluded.info, contacts=excluded.contacts;
insert into companies (id,name,info,contacts) values ('11432','株式会社NTSロジ','{"area": "東京", "country": "インドネシア", "followup": "2024Indonesia視察", "headcount": "1＋6名（在日YST紹介ではない）支援は、7名"}'::jsonb,'[{"name": "笠原", "role": "代表取締役社長", "email": "f_kasahara@nts-group.co.jp"}, {"name": "笠原智久", "role": "取締役　営業企画室", "email": "t_kasahara@nts-group.co.jp"}, {"name": "根岸良成", "role": "取締役", "email": "negisi@nts-group.co.jp"}, {"name": "星住　正", "role": "★実務者　総合管理室　マネージャー", "email": "hosizumi@nts-group.co.jp"}]'::jsonb) on conflict (id) do update set name=excluded.name, info=excluded.info, contacts=excluded.contacts;
insert into companies (id,name,info,contacts) values ('11431','株式会社東邦運輸','{"area": "東京", "features": "豆鉄砲（一般貨物運送業など）", "vehicles": "車両台数：約108台\n従業員数：202名\n免許資格:準中型免許以上", "hp": "https://tohounyu-recruit.com/about/#about01", "country": "インドネシア", "followup": "2024Indonesia視察/2026/2面接", "headcount": "3(2025)＋4(2026)"}'::jsonb,'[{"name": "中島", "role": "代表取締役社長", "email": "h.nakajima@tohounyu.co.jp"}, {"name": "野村 浩", "role": "★実務者　執行役員", "email": "h.nomura@tohounyu.co.jp"}, {"name": "川幡映実", "role": "★実務者　総合管理部　管理・総務リーダー", "email": "a.kawahata@tohounyu.co.jp"}]'::jsonb) on conflict (id) do update set name=excluded.name, info=excluded.info, contacts=excluded.contacts;
insert into companies (id,name,info,contacts) values ('11430','株式会社東洋運輸','{"area": "東京", "features": "豆鉄砲", "country": "インドネシア", "followup": "2024Indonesia視察", "headcount": "2(2025)"}'::jsonb,'[{"name": "中島", "role": "代表取締役", "email": "s.nakajima@tohounyu.co.jp"}, {"name": "石黒", "role": "★実務者　営業部長", "email": "m.ishiguro@tohounyu.co.jp"}]'::jsonb) on conflict (id) do update set name=excluded.name, info=excluded.info, contacts=excluded.contacts;
insert into companies (id,name,info,contacts) values ('11429','ホッコウ物流株式会社','{"area": "北海道・首都圏", "vehicles": "3t・2t／平ボデー／箱車", "country": "インドネシア", "followup": "インドネシア視察（R7.12/4-6）", "headcount": "3(2026)", "resume": "〇", "applicants": "13", "iv_practice": "2025-11-25", "iv_real": "2025-12-04", "offer_planned": "3"}'::jsonb,'[{"name": "井川 真宙", "role": "営業企画部", "email": "m-igawa@hokko-net.co.jp"}, {"name": "郷 雄司", "role": "代表取締役社長COO", "email": "y-go@hokko-net.co.jp"}, {"name": "福岡 忠", "role": "取締役 営業企画部 本州地区担当部長", "email": "fukuoka@hokko-net.co.jp"}, {"name": "梅田純一", "role": "浦安営業所 所長", "email": "j-umeda@hokko-net.co.jp"}]'::jsonb) on conflict (id) do update set name=excluded.name, info=excluded.info, contacts=excluded.contacts;
insert into companies (id,name,info,contacts) values ('11424','凌雲物流株式会社','{"area": "東京", "features": "豆鉄砲", "country": "インドネシア", "headcount": "2(2025)", "offer_planned": "2"}'::jsonb,'[{"name": "田口 典彦", "role": "会長", "email": ""}, {"name": "井田 進", "role": "社長", "email": ""}]'::jsonb) on conflict (id) do update set name=excluded.name, info=excluded.info, contacts=excluded.contacts;
insert into companies (id,name,info,contacts) values ('C11551','サンコー運輸倉庫株式会社','{"area": "横浜", "features": "豆鉄砲（運送・倉庫業）", "vehicles": "車両台数：12台\n従業員数：25名\n免許資格:普通車以上", "hp": "http://www.sanko-35.net/smarts/index/1/", "country": "インドネシア", "followup": "2026/2面接", "headcount": "2(2026)"}'::jsonb,'[{"name": "角田 和志", "role": "代表取締役", "email": "kakuda@sanko-35.jp"}]'::jsonb) on conflict (id) do update set name=excluded.name, info=excluded.info, contacts=excluded.contacts;
insert into companies (id,name,info,contacts) values ('C11552','株式会社緑伸','{"area": "東京", "features": "豆鉄砲(引越・運送業）", "vehicles": "車両台数：約20台\n従業員数：22名\n免許資格:準中型免許以上", "hp": "https://ryokusin.com/", "country": "インドネシア", "followup": "2026/2面接", "headcount": "2(2026)"}'::jsonb,'[{"name": "西牟田 浩一", "role": "代表取締役", "email": "k-nishimuta@t-ryokushin.co.jp"}]'::jsonb) on conflict (id) do update set name=excluded.name, info=excluded.info, contacts=excluded.contacts;

-- 候補者（パイプライン＋要約）
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D001','MOCHAMAD IQBAL PERMANA','MOCHAMAD IQBAL PERMANA','11435','work','','{"local_license": "B1", "ssw_pass": "〇", "passport": "〇", "tk_apply": "完", "employ_cond": "完", "coe_apply": "2025-09-30", "coe_issue": "2025-12-03", "zairyu_permit": "〇", "flight": "〇", "housing": "〇", "guidance_sim": "完", "entry_plan": "2026-02-02", "entered": "1", "work_start": "2026-02-04", "gaimen_apply": "2026-02-24", "gaimen_written": "2026-03-02", "gaimen_skill": "2026-03-25", "driving_school": "―", "license": "2026-03-25", "zairyu_change_apply": "2026-05-30", "zairyu_change_permit": "2026-07-01", "note": "現地、支援中"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "acquired"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D002','CIPTA ADHI TRISNA','CIPTA ADHI TRISNA','11435','work','','{"local_license": "B1", "ssw_pass": "〇", "passport": "〇", "tk_apply": "完", "employ_cond": "完", "coe_apply": "2025-09-30", "coe_issue": "2025-12-03", "zairyu_permit": "〇", "flight": "〇", "housing": "〇", "entry_plan": "2026-02-02", "entered": "1", "work_start": "2026-02-04", "gaimen_apply": "2026-02-24", "gaimen_written": "2026-03-13", "gaimen_skill": "2026-04-20", "driving_school": "―", "license": "2026-04-20", "zairyu_change_apply": "2026-05-30", "zairyu_change_permit": "2026-07-01", "note": "現地、支援中"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "acquired"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D003','ERWIN SETYAWAN','ERWIN SETYAWAN','11433','work','','{"local_license": "B1", "ssw_pass": "〇", "passport": "〇", "tk_apply": "完", "employ_cond": "完", "coe_apply": "2025-09-22", "coe_issue": "2025-12-15", "zairyu_permit": "2026-01-27", "flight": "〇", "housing": "〇", "guidance_sim": "完", "entry_plan": "2026-02-25", "entered": "1", "work_start": "2026-02-27", "gaimen_apply": "2026-04-08", "gaimen_written": "4/27", "gaimen_skill": "6/18", "driving_school": "―", "license": "2026-06-18", "zairyu_change_apply": "来週予定", "note": "特定技能申請準備中"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "acquired"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D004','NANANG HUDA MUSTAKIM','NANANG HUDA MUSTAKIM','11433','injp','','{"local_license": "B1", "ssw_pass": "〇", "passport": "〇", "tk_apply": "完", "employ_cond": "完", "coe_apply": "2025-09-22", "coe_issue": "2025-12-15", "zairyu_permit": "2026-01-27", "flight": "〇", "housing": "〇", "guidance_sim": "完", "entry_plan": "2026-02-25", "entered": "1", "work_start": "2026-02-27", "gaimen_apply": "2026-04-24", "gaimen_written": "5/8", "gaimen_skill": "―", "driving_school": "2026-07-05", "note": "次回の結果次第では合宿免許"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "inprog", "driving_school_note": "2026-07-05"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D005','ACHMAD TAUFIQULHAKIM','ACHMAD TAUFIQULHAKIM','11431','work','','{"local_license": "B1", "ssw_pass": "〇", "passport": "〇", "tk_apply": "完", "employ_cond": "完", "coe_apply": "2025-11-06", "coe_issue": "2026-01-08", "zairyu_permit": "2026-02-20", "flight": "〇", "housing": "〇", "guidance_sim": "2026-02-18", "entry_plan": "2026-03-23", "entered": "1", "gaimen_apply": "2026/4/27", "gaimen_written": "4/27", "gaimen_skill": "5/20", "driving_school": "―", "license": "2026/5/20", "zairyu_change_apply": "2026-07-03", "note": "特技能許可待ち"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "acquired"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D006','IBNU MULYANA','IBNU MULYANA','11431','injp','','{"local_license": "B1", "ssw_pass": "〇", "passport": "〇", "health": "〇", "tk_apply": "2026-05-31", "employ_cond": "完", "coe_apply": "2026-06-29", "entry_plan": "2026/10予"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "notyet"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D007','ALIV','ALIV','11431','injp','','{"local_license": "B1", "ssw_pass": "〇", "passport": "〇", "statement": "免許再発行　3種間～1か月かかる　３－5ジュタかかる　ステートメントレター", "tk_apply": "完", "employ_cond": "完", "coe_apply": "2025-11-06", "coe_issue": "2026-01-08", "zairyu_permit": "2026-02-20", "flight": "〇", "housing": "〇", "guidance_sim": "2026-02-18", "entry_plan": "2026-03-23", "entered": "1", "gaimen_apply": "2026/5/18", "gaimen_written": "5/20", "gaimen_skill": "6/30", "driving_school": "―", "note": "変更書類の押印まち"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "inprog"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D008','AGRAFIN AFIF KRISNOPUTRA','AGRAFIN AFIF KRISNOPUTRA','11431','injp','2期','{"offer_date": "2026-02-21", "local_license": "B1", "ssw_pass": "〇", "statement": "ステートメントレターの訂正依頼　Ny　FTI", "tk_apply": "2026-05-31", "employ_cond": "2026-06-01", "coe_apply": "2026-06-29", "entry_plan": "2026/10予"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "notyet"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D009','SAHAL SANI HARAHAP','SAHAL SANI HARAHAP','11431','injp','2期','{"offer_date": "2026-02-21", "local_license": "B1", "ssw_pass": "〇", "statement": "コミュニケーション　難あり", "tk_apply": "2026-05-31", "employ_cond": "2026-06-01", "coe_apply": "2026-06-29", "entry_plan": "2026/10予"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "notyet"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D010','REZKANDA PUTRA MULYANA','REZKANDA PUTRA MULYANA','11431','injp','2期','{"offer_date": "2026-02-21", "local_license": "B1", "ssw_pass": "〇", "statement": "ステートメントレター外っている", "tk_apply": "2026-05-31", "employ_cond": "2026-06-01", "coe_apply": "取り下げ→東洋", "entry_plan": "2026/10予"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "notyet"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D011','DILAR SAMURAI','DILAR SAMURAI','11431','injp','2期','{"offer_date": "2026-02-21", "local_license": "B1", "ssw_pass": "〇", "statement": "パスポート新しい　要注意", "tk_apply": "2026-05-31", "employ_cond": "2026-06-01", "coe_apply": "2026-06-29", "entry_plan": "2026/10予"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "notyet"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D012','MOHAMAD GALANG BAQIUDIN','MOHAMAD GALANG BAQIUDIN','11430','work','','{"local_license": "B1", "ssw_pass": "〇", "passport": "〇", "tk_apply": "完", "employ_cond": "完", "coe_apply": "2025-11-06", "coe_issue": "2026-01-08", "zairyu_permit": "2026-01-27", "flight": "要手配依頼", "housing": "要手配依頼", "guidance_sim": "完", "entry_plan": "2026-03-30", "entered": "1", "gaimen_apply": "6/2", "gaimen_written": "6/8", "gaimen_skill": "6/18", "driving_school": "―", "license": "6/18", "zairyu_change_apply": "2026-06-23", "note": "変更申請提出中"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "acquired"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D013','TIO AKBAR PANDU SAPUTRA','TIO AKBAR PANDU SAPUTRA','11430','work','','{"local_license": "B1", "ssw_pass": "〇", "passport": "〇", "tk_apply": "完", "employ_cond": "完", "coe_apply": "2025-11-06", "coe_issue": "2026-01-08", "zairyu_permit": "2026-01-27", "flight": "要手配依頼", "housing": "要手配依頼", "guidance_sim": "完", "entry_plan": "2026-03-30", "entered": "1", "gaimen_apply": "5/18", "gaimen_written": "5/20", "gaimen_skill": "6/18", "driving_school": "―", "license": "6/18", "zairyu_change_apply": "2026-06-23", "note": "変更申請提出中"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "acquired"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D014','MUHAMAD RIZKI PUTRA AWALLUDIN','MUHAMAD RIZKI PUTRA AWALLUDIN','11430','pre','2期','{"offer_date": "2026-02-21", "local_license": "A", "ssw_pass": "〇", "statement": "ステートメントレターの進捗　SIMA＋SIMB　の記録を通算でほしい", "tk_apply": "7月末", "employ_cond": "押印待ち"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "notyet"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D015','MUHAMMAD IKHSAN ARYANTO','MUHAMMAD IKHSAN ARYANTO','11430','pre','2期','{"offer_date": "2026-02-21", "local_license": "B1", "ssw_pass": "〇", "statement": "ステートメントレターの進捗　SIMA＋SIMB　の記録を通算でほしい", "tk_apply": "７月末", "employ_cond": "押印待ち"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "notyet"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D016','ANDI WANANDO','ANDI WANANDO','11429','injp','','{"local_license": "B1", "ssw_pass": "〇", "tk_apply": "2026-05-29", "employ_cond": "完", "coe_apply": "2026-05-29", "entry_plan": "2026/9予"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "notyet"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D017','FATRIA SUKMA NUGRAHA','FATRIA SUKMA NUGRAHA','11429','injp','','{"local_license": "B1", "ssw_pass": "〇", "tk_apply": "2026-05-29", "employ_cond": "完", "coe_apply": "2026-05-29", "entry_plan": "2026/9予"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "notyet"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D018','LUKMAN GALIH RAKASIWY','LUKMAN GALIH RAKASIWY','11429','injp','','{"local_license": "B1", "ssw_pass": "〇", "tk_apply": "2026-05-29", "employ_cond": "完", "coe_apply": "2026-05-29", "entry_plan": "2026/9予"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "notyet"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D019','Nanda Rachmansyah','Nanda Rachmansyah','11424','injp','','{"offer_date": "2025-07-24", "contract": "〇", "billing": "〇", "local_license": "B1", "ssw_pass": "〇", "passport": "〇", "health": "●", "mtg3": "〇", "entry_est": "6月", "tk_apply": "2026-02-10", "entry_hope": "6月", "employ_cond": "完", "coe_apply": "2026-02-10", "coe_issue": "2026-04-13", "flight": "2026-05-25", "housing": "完", "entry_plan": "2026-05-26", "entered": "1", "gaimen_apply": "2026-06-11", "gaimen_written": "6/16", "gaimen_skill": "次回7/26"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "inprog"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D020','REKSI MUCHLIS ERLANGGA','REKSI MUCHLIS ERLANGGA','11424','injp','','{"offer_date": "2025-07-24", "contract": "〇", "billing": "〇", "local_license": "B1", "ssw_pass": "〇", "passport": "〇", "health": "◎", "mtg3": "〇", "entry_est": "6月", "tk_apply": "2026-02-10", "entry_hope": "6月", "employ_cond": "完", "coe_apply": "2026-02-10", "coe_issue": "2026-04-13", "flight": "2026-05-25", "housing": "完", "entry_plan": "2026-05-26", "entered": "1", "gaimen_apply": "2026-06-11", "gaimen_written": "6/22", "gaimen_skill": "次回7/26"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "inprog"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D021','PANGKAT PRATAMA SUPIT','PANGKAT PRATAMA SUPIT','11424','injp','','{"offer_date": "2026-02-21", "local_license": "B1", "ssw_pass": "〇", "tk_apply": "7月予定", "employ_cond": "修正中\n７／６予定", "entry_plan": "2026/9～10予"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "notyet"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D022','M. IRHAM SAHARI','M. IRHAM SAHARI','11424','pre','','{"offer_date": "2026-02-21", "local_license": "B1", "ssw_pass": "〇"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "notyet"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D023','ZAKI NURSALAM','ZAKI NURSALAM','11424','pre','','{"offer_date": "2026-02-21", "local_license": "B1", "ssw_pass": "〇"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "notyet"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D024','WANDI WAGINAR','WANDI WAGINAR','11424','pre','','{"offer_date": "2026-02-21", "local_license": "A", "ssw_pass": "〇"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "notyet"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D025','RAI MUHAMAD INDRIYANTO','RAI MUHAMAD INDRIYANTO','C11551','injp','','{"offer_date": "2026-02-21", "local_license": "B1", "ssw_pass": "〇", "tk_apply": "７月17日（木下さん）", "employ_cond": "完", "entry_plan": "2026/9～10予"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "notyet"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D026','RISYAN IDZAKY AZZAM AHMAD','RISYAN IDZAKY AZZAM AHMAD','C11551','pre','','{"offer_date": "2026-02-21", "local_license": "B1", "ssw_pass": "〇", "tk_apply": "７月17日（木下さん）", "employ_cond": "完"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "notyet"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D027','AYUF TIRTANA','AYUF TIRTANA','C11552','injp','','{"offer_date": "2026-02-21", "local_license": "A", "ssw_pass": "〇", "statement": "ドライバー会社の協議会にはいるための条件、安全認定を3－4か月かかる。それがないと協議会にはいれない。\n5月18日　働きやすい職場認証申請済。7月末～8月申請予定。", "tk_apply": "8月", "employ_cond": "押印待ち", "entry_plan": "2026/12予"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "notyet"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
insert into candidates (id,name_ja,name_id,company_id,status,batch,pipeline,ssw,license) values ('D028','FARKHAN KARIMA','FARKHAN KARIMA','C11552','pre','','{"offer_date": "2026-02-21", "local_license": "A", "ssw_pass": "〇", "tk_apply": "8月", "employ_cond": "押印待ち"}'::jsonb,'{"status": "pass"}'::jsonb,'{"final_result": "notyet"}'::jsonb) on conflict (id) do update set name_ja=excluded.name_ja,company_id=excluded.company_id,status=excluded.status,batch=excluded.batch,pipeline=excluded.pipeline,ssw=excluded.ssw,license=excluded.license;
